# constants.py

# Individual column names
PATIENT_ID = "PATIENT_ID"
PROTOCOL_ID = "PROTOCOL_ID"
SESSION_ID = "SESSION_ID"
ADHERENCE = "ADHERENCE"
DM_VALUE = "DM_VALUE"
PE_VALUE = "PE_VALUE"
PPF = "PPF"
USAGE = "USAGE"
DAYS = "DAYS"
GAME_MODE = "GAME_MODE"
SECONDS_FROM_START = "SECONDS_FROM_START"
WEEKDAY_INDEX = "WEEKDAY_INDEX"
PRESCRIPTION_ENDING_DATE = "PRESCRIPTION_ENDING_DATE"
PRESCRIPTION_ACTIVE = "2100-01-01"
DM_KEY = "DM_KEY"
PE_KEY = "PE_KEY"

# Common sets of columns
BY_PP: list[str] = [PATIENT_ID, PROTOCOL_ID] # By Patient–Protocol
BY_PPS: list[str] = [PATIENT_ID, PROTOCOL_ID, SESSION_ID] # By Patient–Protocol–Session
BY_PPST: list[str] = [PATIENT_ID, PROTOCOL_ID, SESSION_ID, SECONDS_FROM_START] # By PPS + Time

# Metrics
FINAL_METRICS = [ADHERENCE, DM_VALUE, PE_VALUE, USAGE, DAYS]
