# constants.py

# Individual column names
PATIENT_ID = "PATIENT_ID"
PROTOCOL_ID = "PROTOCOL_ID"
PRESCRIPTION_ID = "PRESCRIPTION_ID"
SESSION_ID = "SESSION_ID"
ADHERENCE = "ADHERENCE"
DM_VALUE = "DM_VALUE"
PE_VALUE = "PE_VALUE"
PPF = "PPF"
USAGE = "USAGE"
DAYS = "DAYS"
GAME_MODE = "GAME_MODE"
SECONDS_FROM_START = "SECONDS_FROM_START"
WEEKDAY_INDEX = "WEEKDAY_INDEX"
PRESCRIPTION_ENDING_DATE = "PRESCRIPTION_ENDING_DATE"
PRESCRIPTION_ACTIVE = "2100-01-01"
DM_KEY = "DM_KEY"
PE_KEY = "PE_KEY"
SCORE = "SCORE"

# Session columns
SESSION_COLUMNS: list[str] = [
    "SESSION_ID", "STARTING_HOUR", "STARTING_TIME_CATEGORY", "SECONDS_FROM_START", "TOTAL_SUCCESS", "TOTAL_ERRORS", "SCORE"
]

METRIC_COLUMNS: list[str] = [
    "DM_VALUE", "PE_VALUE"
]

TIME_COLUMNS: list[str] = [
    "SESSION_DATE", "STARTING_HOUR", "STARTING_TIME_CATEGORY", "SECONDS_FROM_START"
]

# Common sets of columns
BY_PP: list[str] = [PATIENT_ID, PROTOCOL_ID] # By Patient–Protocol
BY_PPS: list[str] = [PATIENT_ID, PROTOCOL_ID, SESSION_ID] # By Patient–Protocol–Session
BY_PPST: list[str] = [PATIENT_ID, PROTOCOL_ID, SESSION_ID, SECONDS_FROM_START] # By PPS + Time
BY_ID: list[str] = BY_PPS + [PRESCRIPTION_ID] # By Patient–Protocol–Session + Prescription

# Metrics
FINAL_METRICS = [ADHERENCE, DM_VALUE, PE_VALUE, USAGE, DAYS]
