data:
  # Motor Features
  ARAT_GRASP:
    - REACHING
    - GRASPING

  ARAT_GRIP:
    - OBJECT_MANIPULATION

  ARAT_PINCH:
    - PINCHING
    - PRONATION_SUPINATION

  ARAT_GROSS:
    - PROXIMAL_COORDINATION
    - PROCESSING_SPEED
    - MOTOR_PLANNING
    - ROM_VERTICAL
    - ROM_HORIZONTAL

  MOCA_ATTENTION:
    - ATTENTION
    - SUSTAINED_ATTENTION
    - DISTRACTOR_INHIBITION
    - STIMULUS_RESPONSE

  MOCA_VISUO:
    - OBJECT_TRACKING
    - MOTOR_PLANNING_COORDINATION

  MOCA_RECALL:
    - MEMORY_WM
    - RECALL
    - SEMANTIC_MEMORY

  MOCA_NAMING:
    - WORD_RETRIEVAL
    - SEMANTIC_PROCESSING
    - VERBAL_REHEARSAL

  MOCA_LANGUAGE:
    - WORD_RETRIEVAL
    - SEMANTIC_PROCESSING
    - VERBAL_REHEARSAL

  MOCA_ORIENTATION:
    - SPATIAL_CONTEXT

  MOCA_ABSTRACTION:
    - SEMANTIC_GROUPING
    - SEMANTIC_RULE_EXECUTION

keys:
  BARTHEL:
  - Barthel Index
  - BI
  VAS:
  - Visual Analog Scale
  MOCA_VISUO:
  - MoCA.Visuospatial/Executive
  MOCA_NAMING:
  - MoCA.Naming
  MOCA_ATTENTION:
  - MoCA.Attention
  MOCA_LANGUAGE:
  - MoCA.Language
  MOCA_ABSTRACTION:
  - MoCA.Abstraction
  MOCA_RECALL:
  - MoCA.Delayed Recall
  MOCA_ORIENTATION:
  - MoCA.Orientation
