data:
  # Fugl-Meyer Subscales (Motor Control & Coordination)
  FM_A:
    - BODY_PART_ARM
    - BODY_PART_SHOULDER
    - RANGE_OF_MOTION_H
    - RANGE_OF_MOTION_V  # Upper Limb Motor

  FM_B:
    - BODY_PART_WRIST
    - PRONATION_SUPINATION
    - RANGE_OF_MOTION_H  # Wrist Motor

  FM_C:
    - BODY_PART_FINGER
    - GRASPING
    - PINCHING  # Hand Motor

  FM_D:
    - COORDINATION
    - RANGE_OF_MOTION_H
    - RANGE_OF_MOTION_V  # Coordination & Speed

  MOCA_VISUO:
    - VISUALSPATIAL_PROCESSING_AWARENESS_NEGLECT
    - DAILY_LIVING_ACTIVITY

  MOCA_NAMING:
    - VISUAL_LANGUAGE

  MOCA_ATTENTION:
    - ATTENTION
    - MEMORY_WM
    - PROCESSING_SPEED

  MOCA_LANGUAGE:
    - VISUAL_LANGUAGE
    - SYMBOLIC_UNDERSTANDING
    - SEMANTIC_PROCESSING

  MOCA_ABSTRACTION:
    - MATH

  MOCA_RECALL:
    - MEMORY_SEMANTIC

  MOCA_ORIENTATION:
    - COORDINATION

keys:
  BARTHEL:
  - Barthel Index
  - BI
  VAS:
  - Visual Analog Scale
  MOCA_VISUO:
  - MoCA.Visuospatial/Executive
  MOCA_NAMING:
  - MoCA.Naming
  MOCA_ATTENTION:
  - MoCA.Attention
  MOCA_LANGUAGE:
  - MoCA.Language
  MOCA_ABSTRACTION:
  - MoCA.Abstraction
  MOCA_RECALL:
  - MoCA.Delayed Recall
  MOCA_ORIENTATION:
  - MoCA.Orientation
